import os
import yaml

def process_yaml_file(file_path):
    with open(file_path, 'r') as file:
        try:
            data = yaml.safe_load(file)
            print(f"Contents of {file_path}:")
            print(data)
        except yaml.YAMLError as exc:
            print(f"Error processing {file_path}: {exc}")

def run_all_yml(directory):
    for root, _, files in os.walk(directory):
        for file in files:
            if file.endswith(".yml") or file.endswith(".yaml"):
                file_path = os.path.join(root, file)
                process_yaml_file(file_path)

if __name__ == "__main__":
    directory = "path/to/your/yml/files"  # Change this to your directory
    run_all_yml(directory)
